function [Iout] = driverVtoI(Vin)
% computes expected current generated by the driver circuit 
% for the electromagnet
% typical ranges are 1.85 to 1.85 V

R1 = 46200; 
R2 = 999;
R3 = 0.5;

Iout = (1 / R3) * (R2 / (R1 + R2)) * Vin;


end

